# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_auto_20170420_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrecord',
            name='transferID',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
