# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 15:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=20)),
                ('operation', models.BooleanField()),
                ('date', models.DateTimeField()),
                ('comment', models.TextField(null=True)),
                ('target', models.CharField(default='', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferID', models.CharField(max_length=22, unique=True)),
                ('user', models.CharField(max_length=20)),
                ('money', models.DecimalField(decimal_places=2, max_digits=20)),
                ('comment', models.TextField(null=True)),
                ('target', models.CharField(default='', max_length=16)),
                ('process', models.BooleanField()),
            ],
        ),
    ]
