# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accmanage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessrecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='BusinessRecord',
        ),
    ]
