# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accmanage', '0003_auto_20170420_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryrecord',
            name='user',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
